# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mzNmEPmaIra2dyUEBncC8Q1xaOz90WbV
"""

# Importing a library that is not in Colaboratory

!pip install matplotlib-venn

!apt-get -qq install -y libfluidsynth1

!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

!apt-get -qq install -y graphviz && pip install pydot
import pydot

!pip install cartopy
import cartopy

!pip install dash
import dash
print(dash.__version__)

import pandas as pd

url = 'https://docs.google.com/spreadsheets/d/1iLOi4ZaQcBW-OSlkiebhubUEvylY4L0enG9sXlEaUx0/export?format=csv'
df = pd.read_csv(url)

# Cek isi
df.head()

# Ambil data mentah (tanpa kolom normalisasi)
data_mentah = df[['Daya tampung', 'UKT Mandiri']]
data_mentah.head()

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Baca data asli
df = pd.read_excel('coba2.xlsx')
data_mentah = df[['Daya tampung', 'UKT Mandiri']]

# Normalisasi seperti di Orange: [0, 1]
scaler = MinMaxScaler()
X = scaler.fit_transform(data_mentah)

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

wcss = []  # Within-Cluster Sum of Squares
K_range = range(1, 11)  # Uji dari 1 sampai 10 cluster

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10, max_iter=300)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

# Plot hasil Elbow
plt.figure(figsize=(8, 5))
plt.plot(K_range, wcss, marker='o', linestyle='-', color='blue')
plt.title('Elbow Method')
plt.xlabel('Jumlah Cluster (k)')
plt.ylabel('WCSS')
plt.xticks(K_range)
plt.grid(True)
plt.show()

from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

silhouette_scores = [0]  # k=1 tidak valid, jadi kita beri nilai 0
k_values = range(2, 11)

print("Silhouette Scores per k:")
print("k=1: 0.000")  # Cetak nilai dummy untuk k=1

# Mulai dari k=2
for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10, max_iter=300)
    labels = kmeans.fit_predict(X)
    score = silhouette_score(X, labels)
    silhouette_scores.append(score)
    print(f"k={k}: {score:.3f}")  # Cetak nilai silhouette

# Jalankan KMeans final dengan k terbaik
k = 6
kmeans_final = KMeans(n_clusters=k, random_state=42, n_init=10, max_iter=300)
labels = kmeans_final.fit_predict(X)

# Tambahkan hasil cluster ke DataFrame asli
df['Cluster'] = labels

# Tampilkan hasil: Univ + Prodi & Cluster
hasil_cluster = df[['Univ + Prodi', 'Cluster']]
print(hasil_cluster.head(10))

# Simpan ke file Excel
df.to_excel('hasil_clustering_univ_prodi.xlsx', index=False)

# Download di Colab
from google.colab import files
files.download('hasil_clustering_univ_prodi.xlsx')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans

# Ambil kolom mentah
X_raw = df[['Daya tampung', 'UKT Mandiri']]
prodi = df['Univ + Prodi']

# Normalisasi manual
scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X_raw)

# KMeans clustering akhir (misalnya k = 6)
k = 6
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10, max_iter=300)
labels = kmeans.fit_predict(X_norm)

# Buat DataFrame gabungan
X_df = pd.DataFrame(X_norm, columns=['Daya Tampung Normalisasi', 'UKT Normalisasi'])
X_df['Cluster'] = labels
X_df['Univ + Prodi'] = prodi

import matplotlib.pyplot as plt
import seaborn as sns

# Buat DataFrame untuk visualisasi
X_df = pd.DataFrame(X_norm, columns=['Daya Tampung Normalisasi', 'UKT Normalisasi'])
X_df['Cluster'] = labels

# Visualisasi scatter plot per cluster
plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=X_df,
    x='Daya Tampung Normalisasi',
    y='UKT Normalisasi',
    hue='Cluster',
    palette='tab10',
    s=100
)

plt.title('Visualisasi Hasil Clustering K-Means (tanpa label teks)')
plt.xlabel('Daya Tampung (Normalisasi)')
plt.ylabel('UKT Mandiri (Normalisasi)')
plt.grid(True)
plt.legend(title='Cluster')
plt.tight_layout()
plt.show()

df.groupby('Cluster')['UKT Mandiri'].mean().plot(kind='bar', color='skyblue', figsize=(8,5))
plt.title('Rata-rata UKT Mandiri per Cluster')
plt.ylabel('UKT Mandiri')
plt.xlabel('Cluster')
plt.grid(True)
plt.show()

df.groupby('Cluster')['Daya tampung'].mean().plot(kind='bar', color='orange', figsize=(8,5))
plt.title('Rata-rata Daya Tampung per Cluster')
plt.ylabel('Daya Tampung')
plt.xlabel('Cluster')
plt.grid(True)
plt.show()

plt.figure(figsize=(7, 7))
df['Cluster'].value_counts().sort_index().plot(kind='pie', autopct='%1.1f%%', startangle=140, colormap='Set3')
plt.title('Proporsi Prodi per Cluster')
plt.ylabel('')
plt.tight_layout()
plt.show()

cluster_univ = df.groupby(['Cluster', 'Universitas']).size().unstack(fill_value=0)

cluster_univ.plot(kind='bar', stacked=True, figsize=(12, 6), colormap='tab20')
plt.title('Jumlah Prodi per Universitas dalam Tiap Cluster')
plt.xlabel('Cluster')
plt.ylabel('Jumlah Prodi')
plt.legend(title='Universitas', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

import numpy as np

# Hitung rata-rata tiap variabel per cluster
cluster_avg = df.groupby('Cluster')[['Daya tampung', 'UKT Mandiri']].mean()

# Siapkan radar chart
labels = cluster_avg.columns
num_vars = len(labels)

angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
angles += angles[:1]  # Tutup lingkaran

plt.figure(figsize=(8, 8))
for i, row in cluster_avg.iterrows():
    values = row.tolist()
    values += values[:1]
    plt.polar(angles, values, label=f'Cluster {i}')

plt.xticks(angles[:-1], labels)
plt.title('Karakteristik Rata-rata Tiap Cluster')
plt.legend(loc='upper right')
plt.show()

plt.figure(figsize=(10, 6))
sns.heatmap(df.groupby('Cluster')[['Daya tampung', 'UKT Mandiri']].corr(), annot=True, cmap='coolwarm')
plt.title('Korelasi Antar Fitur per Cluster')
plt.show()

import dash
from dash import dcc, html
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Membaca data
df = pd.read_excel('hasil_clustering_univ_prodi.xlsx')

# Menghitung proporsi prodi per cluster
proporsi_prodi = df['Cluster'].value_counts(normalize=True).reset_index()
proporsi_prodi.columns = ['Cluster', 'Proporsi']

# Menghitung jumlah prodi per universitas dalam tiap cluster
jumlah_prodi_univ = df.groupby(['Cluster', 'Universitas']).size().unstack(fill_value=0)

# Menghitung rata-rata tiap variabel per cluster
cluster_avg = df.groupby('Cluster')[['Daya tampung', 'UKT Mandiri']].mean()

# Layout aplikasi
app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Tabs([
        dcc.Tab(label='Clustering', children=[
            html.Div([
                html.H1("Hasil Clustering"),
                dcc.Graph(
                    figure=px.scatter(df, x='Daya tampung', y='UKT Mandiri', color='Cluster',
                                      title='Visualisasi Hasil Clustering K-Means')
                )
            ])
        ]),
        dcc.Tab(label='Rata-rata UKT Mandiri per Cluster', children=[
            html.Div([
                dcc.Graph(
                    figure=px.bar(df.groupby('Cluster')['UKT Mandiri'].mean().reset_index(),
                                  x='Cluster', y='UKT Mandiri', title='Rata-rata UKT Mandiri per Cluster')
                )
            ])
        ]),
        dcc.Tab(label='Rata-rata Daya Tampung per Cluster', children=[
            html.Div([
                dcc.Graph(
                    figure=px.bar(df.groupby('Cluster')['Daya tampung'].mean().reset_index(),
                                  x='Cluster', y='Daya tampung', title='Rata-rata Daya Tampung per Cluster')
                )
            ])
        ]),
        dcc.Tab(label='Proporsi Prodi per Cluster', children=[
            html.Div([
                dcc.Graph(
                    figure=px.pie(proporsi_prodi, values='Proporsi', names='Cluster',
                                  title='Proporsi Prodi per Cluster')
                )
            ])
        ]),
        dcc.Tab(label='Jumlah Prodi per Universitas dalam Tiap Cluster', children=[
            html.Div([
                dcc.Graph(
                    figure=go.Figure(data=[
                        go.Bar(name=univ, x=jumlah_prodi_univ.index, y=jumlah_prodi_univ[univ])
                        for univ in jumlah_prodi_univ.columns
                    ]).update_layout(title='Jumlah Prodi per Universitas dalam Tiap Cluster',
                                     barmode='stack')
                )
            ])
        ]),
        dcc.Tab(label='Karakteristik Rata-rata Tiap Cluster', children=[
            html.Div([
                dcc.Graph(
                    figure=go.Figure(data=[
                        go.Scatterpolar(
                            r=cluster_avg.loc[i].tolist() + [cluster_avg.loc[i].tolist()[0]],  # Close the circle
                            theta=cluster_avg.columns.tolist() + [cluster_avg.columns.tolist()[0]],
                            fill='toself',
                            name=f'Cluster {i}'
                        ) for i in cluster_avg.index
                    ]).update_layout(
                        title='Karakteristik Rata-rata Tiap Cluster',
                        polar=dict(radialaxis=dict(visible=True)),
                        showlegend=True
                    )
                )
            ])
        ]),
        dcc.Tab(label='Korelasi Antar Fitur per Cluster', children=[
            html.Div([
                dcc.Graph(
                    figure=px.imshow(df.groupby('Cluster')[['Daya tampung', 'UKT Mandiri']].corr(),
                                     title='Korelasi Antar Fitur per Cluster',
                                     color_continuous_scale='Viridis')
                )
            ])
        ])
    ])
])

# Menjalankan aplikasi
if __name__ == '__main__':
    app.run(debug=True)
